### ISSUE TITLE
Error on make

### ISSUE THREAD

**Issue by twitherspoon** [compatibleone/accords-platform#31]
I get the following error during the make process.  Any ideas what could be causing this issue.  I also get a ton of warnings about formatting issues, so I'm not sure if that's a problem or not.
# 

Making all in testocci
make[1]: Entering directory `/home/ubuntu/accords-platform-master/testocci'
  CC     testocci-testocci.o
testocci.c: In function ‘handle_request’:
testocci.c:598:25: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
testocci.c:626:29: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
testocci.c:654:20: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  CCLD   testocci
make[1]: Leaving directory`/home/ubuntu/accords-platform-master/testocci'
Making all in testos
make[1]: Entering directory `/home/ubuntu/accords-platform-master/testos'
  CC     testos-testos.o
  CCLD   testos
/home/ubuntu/accords-platform-master/cocci/.libs/libcocci.so: undefined reference to`occi_cords_xthread_builder'
collect2: ld returned 1 exit status
make[1]: **\* [testos] Error 1
make[1]: Leaving directory `/home/ubuntu/accords-platform-master/testos'
make: **\* [all-recursive] Error 1
ubuntu@ip-10-225-184-5:~/accords-platform-master$

**Comment by ijm667** [comment]
This issue has been fixed in the open source repository at github this morning so please pull the corrections and relaunch the build. The issue should be solved but please inform me of any further difficulties.SincerelyJamie Marshall

Date: Thu, 13 Feb 2014 12:20:04 -0800

**Comment by twitherspoon** [comment]
Thanks that worked.  I'm having a different issue now, but I'll create a new one for that.
